name: Build Release Assets

on:
  release:
    types:
      - created

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: ['linux-x64', 'win-x86', 'win-x64', 'osx-x64']
        dotnet: [ '6.0', '7.0', '8.0' ]
    runs-on: ubuntu-latest
    name: Dotnet ${{ matrix.os }}-net${{ matrix.dotnet }} build
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        id: setup_dotnet
        with:
          dotnet-version: '8.0'
      - name: Create temporary global.json
        run: |
          echo '{"sdk":{"version": "${{ steps.setup_dotnet.outputs.dotnet-version }}"}}' > ./global.json
      - name: Build asset
        run: |
          mkdir ./bin
          dotnet publish -c Release -o "./bin/" -r "${{ matrix.os }}" -f "net${{ matrix.dotnet }}${{ startsWith(matrix.os, 'win') && '-windows' || '' }}"
      - name: Compress asset
        run: zip -r ./output.zip ./bin
      - name: Upload asset
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./output.zip
          asset_name: RunDotNetDll-${{ matrix.os }}-net${{ matrix.dotnet }}.zip
          asset_content_type: application/gzip
